import type { getTranslations } from "next-intl/server";
import { HIGH_WEB_MAX, LOW_WEB_MAX, ORIGINAL_WEB_MAX, WEB_MAX } from "@/modules/media/limits";
import type RichTextEditor from "./RichTextEditor";

type Translate = Awaited<ReturnType<typeof getTranslations<"Admin.richText">>>;

/** The editor's control names from the catalogue, shared by both forms that mount it. */
export function richTextEditorLabels(rt: Translate): Parameters<typeof RichTextEditor>[0]["labels"] {
  return {
    bold: rt("bold"),
    italic: rt("italic"),
    heading2: rt("heading2"),
    heading3: rt("heading3"),
    bulletList: rt("bulletList"),
    orderedList: rt("orderedList"),
    quote: rt("quote"),
    align: {
      left: rt("alignLeft"),
      center: rt("alignCenter"),
      right: rt("alignRight"),
    },
    alignShort: {
      left: rt("alignLeftShort"),
      center: rt("alignCenterShort"),
      right: rt("alignRightShort"),
    },
    table: rt("table"),
    tableAddRow: rt("tableAddRow"),
    tableAddColumn: rt("tableAddColumn"),
    tableDeleteRow: rt("tableDeleteRow"),
    tableDeleteColumn: rt("tableDeleteColumn"),
    tableDelete: rt("tableDelete"),
    // Named after the current state, not the action (§263).
    tableBorders: {
      all: rt("tableBordersAll"),
      rows: rt("tableBordersRows"),
      none: rt("tableBordersNone"),
    },
    // One name per state (§271).
    tableBorderColour: {
      default: rt("tableBorderColourDefault"),
      strong: rt("tableBorderColourStrong"),
      blue: rt("tableBorderColourBlue"),
      orange: rt("tableBorderColourOrange"),
    },
    tableHeaderFill: {
      default: rt("tableHeaderFillDefault"),
      none: rt("tableHeaderFillNone"),
      blue: rt("tableHeaderFillBlue"),
      orange: rt("tableHeaderFillOrange"),
    },
    tableValign: rt("tableValign"),
    tableHeaderRow: rt("tableHeaderRow"),
    link: rt("link"),
    linkUrl: rt("linkUrl"),
    linkApply: rt("linkApply"),
    linkRemove: rt("linkRemove"),
    linkCancel: rt("linkCancel"),
    // `rt.raw` here and below: the island fills the placeholders itself (§273).
    words: rt.raw("words") as string,
    preview: rt("preview"),
    previewShort: rt("previewShort"),
    previewClose: rt("previewClose"),
    undo: rt("undo"),
    redo: rt("redo"),
    image: rt("image"),
    imageUploading: rt("imageUploading"),
    imageFailed: rt("imageFailed"),
    // §414, §437.
    imageQuality: {
      legend: rt("imageQualityLegend"),
      low: rt("imageQualityLow"),
      normal: rt("imageQualityNormal"),
      high: rt("imageQualityHigh"),
      original: rt("imageQualityOriginal"),
      help: rt("imageQualityHelp", {
        lowMax: String(LOW_WEB_MAX),
        normalMax: String(WEB_MAX),
        highMax: String(HIGH_WEB_MAX),
        originalMax: String(ORIGINAL_WEB_MAX),
      }),
    },
    imageChoose: rt("imageChoose"),
    imageChosen: {
      chosen: rt.raw("imageChosen") as string,
      sent: rt.raw("imageSent") as string,
      lighter: rt.raw("imageLighter") as string,
    },
    imagePixels: rt.raw("imagePixels") as string,
    imageStored: {
      template: rt.raw("imageStored") as string,
      topRung: rt.raw("imageStoredTopRung") as string,
      low: rt("imageStoredLow"),
      normal: rt("imageStoredNormal"),
      high: rt("imageStoredHigh"),
      original: rt("imageStoredOriginal"),
      nearLossless: rt.raw("imageStoredNearLossless") as string,
    },
    imageAlt: rt("imageAlt"),
    imageAltHelp: rt("imageAltHelp"),
    imageCaption: rt("imageCaption"),
    imageSize: rt("imageSize"),
    imageAlign: rt("imageAlign"),
    imageAlignBlock: rt("imageAlignBlock"),
    imageAlignLeft: rt("imageAlignLeft"),
    imageAlignRight: rt("imageAlignRight"),
    imageAlignHelp: rt("imageAlignHelp"),
    imageCrop: rt("imageCrop"),
    imageCropHelp: rt("imageCropHelp"),
    imageCropReset: rt("imageCropReset"),
    imageCropPosition: rt.raw("imageCropPosition") as string,
    // The shapes and the card's centre (§454).
    imageShapes: {
      presets: rt("imageShapes"),
      preset: {
        free: rt("imageShapeFree"),
        "16:9": rt("imageShape169"),
        "4:3": rt("imageShape43"),
        "1:1": rt("imageShape11"),
        "4:5": rt("imageShape45"),
      },
      target: rt("imageCropTarget"),
      targetCrop: rt("imageCropTargetCrop"),
      targetFocus: rt("imageCropTargetFocus"),
      focusHelp: rt("imageFocusHelp"),
      focusReset: rt("imageFocusReset"),
      focusPosition: rt.raw("imageFocusPosition") as string,
      cardPreview: rt("imageCardPreview"),
    },
    imageUploadShapeHelp: rt("imageUploadShapeHelp"),
    imageUploadCropped: rt.raw("imageUploadCropped") as string,
    imageRemove: rt("imageRemove"),
    imageDone: rt("imageDone"),
    imageClose: rt("imageClose"),
    imagePanel: rt("imagePanel"),
    imageNoAltOne: rt("imageNoAltOne"),
    imageNoAltMany: rt.raw("imageNoAltMany") as string,
    imageFromGallery: rt("imageFromGallery"),
    imageShort: rt("imageShort"),
    imageFromGalleryShort: rt("imageFromGalleryShort"),
    imageGalleryLoading: rt("imageGalleryLoading"),
    imageGalleryEmpty: rt("imageGalleryEmpty"),
    imageGalleryClose: rt("linkCancel"),
    imageGalleryFilter: rt("imageGalleryFilter"),
    imageGalleryNoMatch: rt("imageGalleryNoMatch"),
    imageGallerySourceLegend: rt("imageGallerySourceLegend"),
    imageGallerySources: {
      all: rt("imageGallerySourceAll"),
      event: rt("imageGallerySourceEvent"),
      album: rt("imageGallerySourceAlbum"),
      page: rt("imageGallerySourcePage"),
      team: rt("imageGallerySourceTeam"),
    },
    // The first chip: the text's own place (§485).
    imageGalleryHere: {
      event: rt("imageGalleryHereEvent"),
      album: rt("imageGalleryHereAlbum"),
      page: rt("imageGalleryHerePage"),
    },
    imageFromGalleryPicked: rt.raw("imageFromGalleryPicked") as string,
    youtube: rt("youtube"),
    youtubeShort: rt("youtubeShort"),
    youtubeUrl: rt("youtubeUrl"),
    youtubeApply: rt("youtubeApply"),
    youtubeInvalid: rt("youtubeInvalid"),
    youtubeCaption: rt("youtubeCaption"),
    youtubeRemove: rt("youtubeRemove"),
    youtubePoster: rt("youtubePoster"),
    youtubePosterUploading: rt("youtubePosterUploading"),
    youtubePosterFailed: rt("youtubePosterFailed"),
    youtubePosterUseYoutube: rt("youtubePosterUseYoutube"),
    youtubePosterFromGallery: rt("youtubePosterFromGallery"),
    youtubePosterCrop: rt("youtubePosterCrop"),
    youtubePosterCropHelp: rt("youtubePosterCropHelp"),
    youtubePosterCropReset: rt("youtubePosterCropReset"),
    youtubePosterCropWaiting: rt("youtubePosterCropWaiting"),
  };
}
