import { z } from "zod";
import { EMPTY_DOC, parseRichText } from "@/modules/content/rich-text/domain/schema";
import { routing } from "@/i18n/routing";
import { refuseOneLanguage } from "@/shared/forms/both-languages";

/**
 * What an organizer types into the page editor (BR-REQ-050-03).
 *
 * The body arrives as **text**, not as the structured JSON the column stores: the editor is a
 * textarea and `legal-documents/domain/body-text.ts` converts in both directions. That module is
 * reused rather than copied, and reused rather than generalised — `AGENTS.md` §1.5 abstracts on
 * the third occurrence, and this is the second.
 */

/** Lowercase, digits and hyphens. What a URL can carry without escaping and a person can read. */
const slug = z
  .string()
  .trim()
  .min(1)
  .max(120)
  .regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/, "a page address may use only lowercase letters, digits and hyphens");

/**
 * Reserved first segments, refused as page slugs.
 *
 * A page at `/pagini/admin` would not collide with the backoffice — different prefix — but it
 * reads as one, and a visitor who lands there having typed a path from memory is owed a 404
 * rather than a club page pretending to be a system route.
 */
const RESERVED_SLUGS = new Set(["admin", "api", "devs", "preview", "previzualizare", "new"]);

const optionalText = (max: number) =>
  z
    .string()
    .trim()
    .max(max)
    .transform((value) => (value === "" ? null : value));

export const pageTranslationSchema = z.object({
  slug: slug.refine((value) => !RESERVED_SLUGS.has(value), "this page address is reserved"),
  title: z.string().trim().min(1).max(200),
  /** Free text in the blank-line/`## ` format. Empty is allowed: a page may be drafted title-first. */
  /**
   * The body arrives as a JSON string — what `RichTextEditor` puts in its hidden input — and
   * leaves this schema as a validated document (`AGENTS.md` §11.3). Parsed here rather than in
   * the service so that an unparseable body is a field error beside the field, like every other
   * validation failure, instead of an exception halfway through a transaction.
   *
   * The limit is on the JSON, which is several times longer than the words in it: ProseMirror
   * spends about forty characters wrapping every paragraph. 200k is a very long page and still
   * refuses a body somebody generated by accident.
   */
  body: z
    .string()
    .max(200_000)
    .transform((value, ctx) => {
      // A page with nothing in it yet. Publication is what refuses an empty body, and it says
      // which language is missing (§11.2) — a far better answer than "not a valid document".
      if (value.trim() === "") return EMPTY_DOC;
      try {
        return parseRichText(JSON.parse(value));
      } catch {
        ctx.addIssue({ code: "custom", message: "the body is not a valid document" });
        return z.NEVER;
      }
    }),
  seoTitle: optionalText(200),
  seoDescription: optionalText(400),
});

export type PageTranslationInput = z.infer<typeof pageTranslationSchema>;

/**
 * Both languages, always, in one object.
 *
 * Publication is one state for the whole page and requires every locale to be complete
 * (`AGENTS.md` §11.2), so the editor asks for both from the beginning rather than letting a page
 * exist in one language and discover the rule at the moment somebody tries to publish it.
 *
 * The two search-engine texts are optional, and optional in both languages at once (§NNN,
 * bilingual everywhere — the rule the event's own two overrides follow): a title or a description
 * for Google written in one language and left empty in the other is refused on the empty box,
 * every other box kept (§315). The editor posts both languages in one save, so the rule is read
 * here, where both are known, and never has to wait for a second save.
 */
export const pageFieldsSchema = z.object({
  navOrder: z
    .string()
    .trim()
    .transform((value) => (value === "" ? 0 : Number(value)))
    .pipe(z.number().int().min(0).max(1000)),
  translations: z
    .object(
      Object.fromEntries(routing.locales.map((locale) => [locale, pageTranslationSchema])) as Record<
        (typeof routing.locales)[number],
        typeof pageTranslationSchema
      >,
    )
    .superRefine((translations, ctx) => {
      for (const field of ["seoTitle", "seoDescription"] as const) {
        refuseOneLanguage(
          ctx,
          { ro: translations.ro[field], en: translations.en[field] },
          { ro: ["ro", field], en: ["en", field] },
          `the page's ${field === "seoTitle" ? "search-engine title" : "search-engine description"}`,
        );
      }
    }),
});

export type PageFieldsInput = z.infer<typeof pageFieldsSchema>;
